### ISSUE TITLE
Allow the user to control the `temperature` of the ai model via a flag

### ISSUE THREAD

**Issue by peterdanwan** [AryanK1511/github-echo#27]
Per our discussion, we can try to make your command-line tool more flexible by letting the user specify the "temperature" of the AI model.

<https://github.com/AryanK1511/github-echo/blob/8710dde5ad440d6892a835c823a97b7f41d52728/application/utils/gemini_config.py#L53-L58>

**Comment by AryanK1511** [comment]
@peterdanwan the ability to specify the temperature via command line options has been added. Will be releasing the new version soon for everyone to download.
