### ISSUE TITLE
Containerize the application using Docker

### ISSUE THREAD

**Issue by peterdanwan** [AryanK1511/github-echo#28]
As a suggestion for users that are uncomfortable with handling their different Python environments it might be nice to have a Dockerized version of your code to handle the execution environment, as opposed to relying on users to setup a `conda`  or `Python3` environment themselves.

**Comment by AryanK1511** [comment]
@peterdanwan I have setup a [`Dockerfile`](https://github.com/AryanK1511/github-echo/blob/main/Dockerfile) and have also modified the [CI pipeline](https://github.com/AryanK1511/github-echo/blob/main/.github/workflows/ci.yml) to contain Dockerfile listing using [`Hadolint`](https://github.com/hadolint/hadolint).

Thanks for bringing this up 😀. Closing this issue now!!
