### ISSUE TITLE
Initialize a testing framework + updating your ci pipeline

### ISSUE THREAD

**Issue by peterdanwan** [AryanK1511/github-echo#29]
Like we discussed, your `ci.yml`, currently automates the process of checking if your source code is formatted properly or not.
We can add a _new_ job that involves testing your code automatically.

Once you have a basic test (doesn't need to be a real test), we can test your `ci.yml`'s logic by pushing your code to GitHub to see if it actually tries to run your tests.

If the `ci pipeline` works, this could gear your project towards better test-driven development.

**Comment by AryanK1511** [comment]
Thanks @peterdanwan  for opening this issue. I have initialized [`pytest`](https://docs.pytest.org/en/stable/) and have also updated the CI pipeline. 

- https://github.com/AryanK1511/github-echo/tree/main/tests
- https://github.com/AryanK1511/github-echo/blob/main/.github/workflows/ci.yml

Closing the issue now.

**Comment by peterdanwan** [comment]
That looks great! Let me know if you wish to discuss later.
