### ISSUE TITLE
Structure prompt output

### ISSUE THREAD

**Issue by RiverDave** [AryanK1511/github-echo#37]
Hi there, first of all gotta say congratulations! I stumbled upon your project and it seems active, well structured and the idea definitely has ton of potential! [I've been experimenting](https://github.com/RiverDave/ADVision-API) these last couple of days with the popular LLM API's and I thought this would be a great opportunity to contribute.

Lets get to the Grain!, I think you'd benefit immensely from structuring your prompt in this [file](https://github.com/AryanK1511/github-echo/blob/main/application/utils/gemini_config.py#L19) By breaking down complex data (such as the prompt instructions) into smaller, structured pieces(Fortunately this is supported by the Gemini API), you can improve readability, reduce repetition, and facilitate easier modifications or expansions in the future.  You'd also reduce hallucinations in your generation which at the end will make the generations much more consistent.

I'd like to know what you think, I don't mind sending a pull request on this issue. If so I'll be looking forward to contribute on your project consistently.

**Comment by AryanK1511** [comment]
Hello @RiverDave, thank you for your feedback. I think your idea is great but I am not really clear on what you mean by "breaking down intro structured pieces". Feel free to make some changes and send in a PR. Id love to test your changes and see how they improves the program.

**Comment by AryanK1511** [comment]
Great work @RiverDave. I have merged the PR and we are all good to go!!!
