### ISSUE TITLE
Consider showing sub-tasks vs. only progress bar

### ISSUE THREAD

**Issue by humphd** [AryanK1511/github-echo#39]
When analyzing a repo, you show a progress bar, but that takes a long time.  You might consider having sub-tasks print out, so it updates more quickly (e.g., it shows the different API calls finishing).

**Comment by AryanK1511** [comment]
This sounds like a good option! I knew the progress bar was not the best choice but it looked pretty cool so I decided to try it out. 

I will take you up on your suggestion and push a change sometime in the next week to show subtasks instead of a progress bar.

**Comment by AryanK1511** [comment]
Fixed. Now the progress bar is replaced by a spinner like so:

![Screenshot 2024-09-19 at 2 40 56 PM](https://github.com/user-attachments/assets/aedd5da4-8a7c-4bb5-bbf8-07d82854b7d8)

Thanks for bringing this up @humphd.
