### ISSUE TITLE
Add Command-Line Flag for Token Usage Information

### ISSUE THREAD

**Issue by hpatel292-seneca** [AryanK1511/github-echo#41]
# Add a Command-Line Option to Show Token Usage

## Description
When working with large language models (LLMs), it's essential to know how many tokens you're using in each request and response. This not only helps in managing costs but also ensures that you stay within the model's context limit.

To make this easier, I'd like to add a new command-line option: `--token-usage` (or `-t` for short). When you run the program with this option, it will print extra details to `stderr` about the number of tokens used — both those sent in the prompt and those returned in the completion.

Here's what the output would look like:

- **`completion_tokens`**: Tokens used in the generated response.
- **`prompt_tokens`**: Tokens used in the initial prompt.
- **`total_tokens`**: Total tokens used (the sum of prompt and completion tokens).

For example, a typical response from OpenAI might include:

```json
{
  "completion_tokens": 17,
  "prompt_tokens": 57,
  "total_tokens": 74
}
```
This information is invaluable for debugging and optimizing your use of the API. I’d like to work on adding this feature and would appreciate any guidance or suggestions you have on the best way to implement it.

**Comment by AryanK1511** [comment]
Thank you for working on this!
